question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The 'forbidden fruit' in Genesis is an apple.", "answer": "False"},
    {"text": "The total surface area of a human lungs is the size of a soccer field.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, "
             "you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
     "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "The dot over 'i' and 'j' is called a tittle.", "answer": "True"},
    {"text": "A penny dropped from the empire state building can kill a person on the sidewalk.", "answer": "False"},
    {"text": "Toilet flushes spin different directions in different hemispheres.", "answer": "False"},
    {"text": "Bananas do not actually grow on trees.", "answer": "True"},
    {"text": "Human beings evolved from apes.", "answer": "False"},
    {"text": "The single largest organism is a mushroom.", "answer": "True"},
    {"text": "A severed earth worm will regenerate as two earth worms.", "answer": "False"},
    {"text": "The bald eagle can see the farthest out of every living organism.", "answer": "True"},
    {"text": "Houseflies only live for 24 hours.", "answer": "False"},
    {"text": "A dog's mouth is cleaner than a humans.", "answer": "False"},
    {"text": "Harris hawks can see the most colors out of any animal.", "answer": "False"},
    {"text": "Witches during the Salem Witch Trials were hanged.", "answer": "True"},
    {"text": "Humans need to drink eight glasses of water every day.", "answer": "False"},
    {"text": "It is illegal to set a mouse trap without a hunting license in California.", "answer": "True"},
    {"text": "Only humans can blush.", "answer": "True"},
    {"text": "There have been Tinder matches on every continent in the world.", "answer": "True"},
    {"text": "The most viewed YouTube video is Despacito.", "answer": "False"}
    ]
